### PR TITLE
Update shopify

### PR DESCRIPTION
**Pull request by potocnyj**

### CODE REVIEW

**Comment by potocnyj** [comment]
@ElPeque @gkristic this isn't practical to review but I successfully ran the consumers with this branch of sarama on staging for a few days, any concerns about merging?

If you're curious what actually changes, we're going from v1.4.1 to v1.7, the release notes at https://github.com/Shopify/sarama/releases give a good idea of what the improvements are.

**Comment by ElPeque** [comment]
Provided you've been trying them in staging for i a while i wouldn't object
trying them in prod.

Did you see any improvements in performance? Just curious :)
​

**Comment by potocnyj** [comment]
No noticeable improvement on stage, but v1.6.0 introduced a faster CRC32 implementation that I vendored as part of this PR, I estimate it will improve consumer performance by ~10% across all consumers and also make producers a couple percent faster.

**Comment by gkristic** [comment]
Yes, absolutely impractical to review :)

If you've tried in stage and it works, let's go ahead and push to prod.

**Pull request merged**
