### PR TITLE
5127 forking sarama

### PR DESCRIPTION
**Pull request by talklainersamanage**
Sync our fork with Shopify/sarama

Ref: VividCortex/artifacts#5127

### CODE REVIEW

**Comment by efepapa** [comment]
The local `queue` package is [no longer used](https://github.com/VividCortex/sarama/blob/31a38f0a819c7cde8f9a302ce801218c2b5117f9/async_producer.go#L10).

**Comment by pmatseykanets** [comment]
Import paths should point to 

```
github.com/Shopify/sarama
```

instead of 

```
github.com/VividCortex/sarama
```

The substitution should be done via the package/dependency management tool  as in `dep`

```
[[constraint]]
  name = "github.com/VividCortex/sarama"
  source = "github.com/Shopify/sarama"
  version = "=1.26.4"
```

or as in `go modules`

```
replace (
	github.com/VividCortex/sarama => github.com/VividCortex/sarama v1.26.4
)
```

**Comment by bashcraftvc** [comment]
Is this PR ready to merge? @talklainersamanage @pmatseykanets

**Comment by talklainersamanage** [comment]
Hi @bashcraftvc 
I think this PR is waiting @presstartgames approval
Also I do not think we will merge this PR to master until we check it on production (use this code in producer and consumer on production environment)

**Comment by presstartgames** [comment]
I'm assuming my ping [here](https://github.com/VividCortex/sarama/pull/19#issuecomment-647092323) was meant for Peter, but let me know if I am being needed for anything regarding this ticket.

**Comment by talklainersamanage** [comment]
> I'm assuming my ping [here](https://github.com/VividCortex/sarama/pull/19#issuecomment-647092323) was meant for Peter, but let me know if I am being needed for anything regarding this ticket.

Yes sorry

**Pull request merged**
